language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - RUST_BACKTRACE=1
script:
  - cargo test --verbose --features 'less-slow-kanji-encode less-slow-big5-hanzi-encode less-slow-gb-hanzi-encode serde'
  - cargo test --verbose
